CREATE TABLE merchants (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) NOT NULL,
    tax_number varchar(9) NOT NULL,
    login varchar(255) NOT NULL,
    password varchar(80) NOT NULL,
    is_active boolean DEFAULT TRUE,
    --
    -- timestamps
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    --
    -- constraints
    CONSTRAINT uk_merchants_tax_number UNIQUE (tax_number),
    CONSTRAINT uk_merchants_login UNIQUE (login)
);

CREATE TABLE merchant_commissions (
   id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   merchant_id bigint NOT NULL,
   commission_rate NUMERIC(5, 4) NOT NULL,
   is_active boolean DEFAULT TRUE,
   --
   -- timestamps
   created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
   --
   -- relations
   CONSTRAINT fk_merchant FOREIGN KEY (merchant_id) REFERENCES merchants (id) ON DELETE CASCADE
);

CREATE TABLE meals (
   id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   name varchar(255) NOT NULL,
   description text DEFAULT NULL,
   price bigint NOT NULL,
   merchant_id bigint NOT NULL,
   is_active boolean DEFAULT TRUE,
   --
   -- timestamps
   created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
   updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
   --
   -- relations
   CONSTRAINT fk_merchant FOREIGN KEY (merchant_id) REFERENCES merchants (id) ON DELETE CASCADE
);


CREATE TABLE waiters (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name varchar(255) NOT NULL,
    login varchar(255) NOT NULL,
    password varchar(80) NOT NULL,
    merchant_id bigint NOT NULL,
    is_active boolean DEFAULT TRUE,
    --
    -- timestamps
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    --
    -- relations
    CONSTRAINT fk_merchant FOREIGN KEY (merchant_id) REFERENCES merchants (id) ON DELETE CASCADE
);


CREATE TABLE tables (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    merchant_id bigint NOT NULL,
    table_number varchar(255) NOT NULL,
    --
    -- constraints
    CONSTRAINT uk_merchants_table_number UNIQUE (merchant_id, table_number),
    --
    -- relations
    CONSTRAINT fk_merchant FOREIGN KEY (merchant_id) REFERENCES merchants (id) ON DELETE CASCADE
);

CREATE TYPE order_status AS ENUM (
    'OPEN',
    'PAID',
    'CANCELED'
);

CREATE TABLE orders (
   id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   waiter_id bigint NOT NULL,
   table_id bigint NOT NULL,
   status order_status NOT NULL DEFAULT 'OPEN',
   --
   -- timestamps
   created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
   updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
   --
   -- relations
   CONSTRAINT fk_waiter FOREIGN KEY (waiter_id) REFERENCES waiters(id) ON DELETE RESTRICT,
   CONSTRAINT fk_table FOREIGN KEY (table_id) REFERENCES tables(id) ON DELETE RESTRICT
);

CREATE TABLE guests (
   id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   order_id bigint NOT NULL,
   --
   -- timestamps
   created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
   --
   -- relations
   CONSTRAINT fk_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE RESTRICT
);

CREATE TABLE order_items (
   id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   order_id bigint NOT NULL,
   guest_id bigint DEFAULT NULL,
   meal_id bigint NOT NULL,
   meal_price bigint NOT NULL CHECK (meal_price > 0),
   quantity INTEGER NOT NULL CHECK (quantity > 0),
   --
   -- timestamps
   created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
   updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
   --
   -- constraints
   CONSTRAINT uk_order_item_order_guest_meal UNIQUE (order_id, guest_id, meal_id),
   --
   -- relations
   CONSTRAINT fk_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE RESTRICT,
   CONSTRAINT fk_guest FOREIGN KEY (guest_id) REFERENCES guests(id) ON DELETE RESTRICT,
   CONSTRAINT fk_meal FOREIGN KEY (meal_id) REFERENCES meals(id) ON DELETE RESTRICT
);


CREATE TYPE user_role_enum AS ENUM (
    'MERCHANT',
    'WAITER'
);


CREATE TABLE refresh_token_entity (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token varchar(255) NOT NULL UNIQUE,
    expiry_date TIMESTAMP WITH TIME ZONE,
    subject VARCHAR(255) NOT NULL,
    user_role user_role_enum NOT NULL
);